spring:
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/auth_db
    password: root
    username: noleg
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

token:
  signing:
    key: ${TOKEN_SINGING_KEY:53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855}
  expiration: ${TOKEN_EXPIRATION:3600000}

app:
  admin:
    password: ${DEFAULT_ADMIN_PASSWORD:admin123}